"""
날씨 데이터 및 위치 정보 매핑을 위한 모델 모듈
"""

# 날씨 코드 설명 매핑
PTY_CODES = {
    "0": "없음",
    "1": "비",
    "2": "비/눈",
    "3": "눈",
    "5": "빗방울",
    "6": "빗방울눈날림",
    "7": "눈날림"
}

SKY_CODES = {
    "1": "맑음",
    "3": "구름많음",
    "4": "흐림"
}

# 지역 정보 데이터 (주요 도시)
CAPITAL_LOCATION = [
    {
        "administrativeArea": "Seoul",
        "administrativeAreaKorean": "서울특별시",
        "capitalNX": 60,
        "capitalNY": 127,
        "koreanName": "서울",
        "midAreaNumber": "11B00000",
    },
    {
        "administrativeArea": "Busan",
        "administrativeAreaKorean": "부산광역시",
        "capitalNX": 98,
        "capitalNY": 76,
        "koreanName": "부산",
        "midAreaNumber": "11H20000",
    },
    {
        "administrativeArea": "Daegu",
        "administrativeAreaKorean": "대구광역시",
        "capitalNX": 89,
        "capitalNY": 90,
        "koreanName": "대구",
        "midAreaNumber": "11H10000",
    },
    {
        "administrativeArea": "Incheon",
        "administrativeAreaKorean": "인천광역시",
        "capitalNX": 55,
        "capitalNY": 124,
        "koreanName": "인천",
        "midAreaNumber": "11B00000",
    },
    {
        "administrativeArea": "Gwangju",
        "administrativeAreaKorean": "광주광역시",
        "capitalNX": 58,
        "capitalNY": 74,
        "koreanName": "광주",
        "midAreaNumber": "11F20000",
    },
    {
        "administrativeArea": "Daejeon",
        "administrativeAreaKorean": "대전광역시",
        "capitalNX": 67,
        "capitalNY": 100,
        "koreanName": "대전",
        "midAreaNumber": "11C20000",
    },
    {
        "administrativeArea": "Ulsan",
        "administrativeAreaKorean": "울산광역시",
        "capitalNX": 102,
        "capitalNY": 84,
        "koreanName": "울산",
        "midAreaNumber": "11H20000",
    },
    {
        "administrativeArea": "Sejong-si",
        "administrativeAreaKorean": "세종특별자치시",
        "capitalNX": 66,
        "capitalNY": 103,
        "koreanName": "세종",
        "midAreaNumber": "11C20000",
    },
    {
        "administrativeArea": "Gyeonggi-do",
        "administrativeAreaKorean": "경기도",
        "capitalNX": 60,
        "capitalNY": 120,
        "koreanName": "경기도",
        "midAreaNumber": "11B00000",
    },
    {
        "administrativeArea": "Gangwon-do",
        "administrativeAreaKorean": "강원특별자치도",
        "capitalNX": 73,
        "capitalNY": 134,
        "koreanName": "강원도",
        "midAreaNumber": "11D10000",
    },
    {
        "administrativeArea": "Chungcheongbuk-do",
        "administrativeAreaKorean": "충청북도",
        "capitalNX": 69,
        "capitalNY": 107,
        "koreanName": "충청북도",
        "midAreaNumber": "11C10000",
    },
    {
        "administrativeArea": "Chungcheongnam-do",
        "administrativeAreaKorean": "충청남도",
        "capitalNX": 68,
        "capitalNY": 100,
        "koreanName": "충청남도",
        "midAreaNumber": "11C20000",
    },
    {
        "administrativeArea": "Jeollabuk-do",
        "administrativeAreaKorean": "전북특별자치도",
        "capitalNX": 63,
        "capitalNY": 89,
        "koreanName": "전라북도",
        "midAreaNumber": "11F10000",
    },
    {
        "administrativeArea": "Jeollanam-do",
        "administrativeAreaKorean": "전라남도",
        "capitalNX": 51,
        "capitalNY": 67,
        "koreanName": "전라남도",
        "midAreaNumber": "11F20000",
    },
    {
        "administrativeArea": "Gyeongsangbuk-do",
        "administrativeAreaKorean": "경상북도",
        "capitalNX": 89,
        "capitalNY": 91,
        "koreanName": "경상북도",
        "midAreaNumber": "11H10000",
    },
    {
        "administrativeArea": "Gyeongsangnam-do",
        "administrativeAreaKorean": "경상남도",
        "capitalNX": 91,
        "capitalNY": 77,
        "koreanName": "경상남도",
        "midAreaNumber": "11H20000",
    },
    {
        "administrativeArea": "Jeju-do",
        "administrativeAreaKorean": "제주특별자치도",
        "capitalNX": 52,
        "capitalNY": 38,
        "koreanName": "제주",
        "midAreaNumber": "11G00000",
    },
    # 주요 도시들 추가
    {
        "administrativeArea": "Chuncheon",
        "administrativeAreaKorean": "춘천시",
        "capitalNX": 73,
        "capitalNY": 134,
        "koreanName": "춘천",
        "midAreaNumber": "11D10000",
    },
    {
        "administrativeArea": "Gangneung",
        "administrativeAreaKorean": "강릉시",
        "capitalNX": 92,
        "capitalNY": 131,
        "koreanName": "강릉",
        "midAreaNumber": "11D20000",
    },
    {
        "administrativeArea": "Cheongju",
        "administrativeAreaKorean": "청주시",
        "capitalNX": 69,
        "capitalNY": 106,
        "koreanName": "청주",
        "midAreaNumber": "11C10000",
    },
    {
        "administrativeArea": "Jeonju",
        "administrativeAreaKorean": "전주시",
        "capitalNX": 63,
        "capitalNY": 89,
        "koreanName": "전주",
        "midAreaNumber": "11F10000",
    },
    {
        "administrativeArea": "Cheonan",
        "administrativeAreaKorean": "천안시",
        "capitalNX": 63,
        "capitalNY": 110,
        "koreanName": "천안",
        "midAreaNumber": "11C20000",
    },
    {
        "administrativeArea": "Boryeong",
        "administrativeAreaKorean": "보령시",
        "capitalNX": 54,
        "capitalNY": 100,
        "koreanName": "보령",
        "midAreaNumber": "11C20000",
    },
    {
        "administrativeArea": "Gongju",
        "administrativeAreaKorean": "공주시",
        "capitalNX": 63,
        "capitalNY": 102,
        "koreanName": "공주",
        "midAreaNumber": "11C20000",
    },
]